max-acc-per-ip: 2
messages:
  require-auth: "&eSử dụng &b%cmd% &eđể tiếp tục!"
  register-success: "&aĐăng ký thành công!"
  login-success: "&aĐăng nhập thành công!"
  wrong-password: "&cSai mật khẩu rồi!"
  already-registered: "&cBạn đã đăng ký rồi!"
  not-registered: "&cBạn chưa đăng ký!"
  password-not-match: "&cMật khẩu không khớp!"
  max-ip-reached: "&cIP này đã đạt giới hạn %limit% tài khoản!"
