name: ArisAuthme
version: 1.0
main: me.VennLMAO.ArisAuthme.ArisAuthme
api-version: 1.20
author: VennLMAO
folia-supported: true
commands:
  dangky:
    description: Dang ky tai khoan
  dangnhap:
    description: Dang nhap tai khoan
